[Scouting] Improve readability and efficiency
idealo/deckard pull request #8
Opened 2022-02-04 15:26 UTC by strahinja-misic

Small contribution to the project

2022-02-04 15:50 UTC, strahinja-misic commented
@marcus-j Trying to figure out what is going on. 'mvn clean verify' runs without any issues locally for both my branch and master but if I run the test method individually it fails. Also, test itself has nothing to do with my changes...

2022-02-04 15:55 UTC, marcus-j commented
@strahinja-misic I believe we saw this previously happen as well. I also believe that your changes do not cause this. Still, if you have time, feel free to look into it :)

2022-02-04 17:25 UTC, roechi approved these changes
Looks great! Thanks for your engagement!

2022-03-14 14:16 UTC, strahinja-misic commented
@marcus-j Could you take a look at this PR when you have time?

2022-03-14 15:36 UTC, marcus-j commented
> @marcus-j Could you take a look at this PR when you have time?

@strahinja-misic I did leave two comments a while back (see above):

![image](https://user-images.githubusercontent.com/18111840/158207111-460865e5-76e2-4792-b70b-7baa4d631879.png)

2022-03-22 09:52 UTC, strahinja-misic commented
@marcus-j In case you have written additional comments I just wanted to say that I do not see any for some reason.

2022-03-22 11:52 UTC, marcus-j requested changes

2022-03-22 11:53 UTC, marcus-j commented
> @marcus-j In case you have written additional comments I just wanted to say that I do not see any for some reason.

Damn, forgot to finish that review and GH hides the comments that have been made during that :/ Sorry!

2022-03-22 12:37 UTC, strahinja-misic commented on src/main/java/de/idealo/kafka/deckard/proxy/ProducerProxyBeanFactory.java
> +            return !password.isEmpty() && !salt.isEmpty();
Fixed.

2022-03-22 12:38 UTC, strahinja-misic commented on src/main/java/de/idealo/kafka/deckard/proxy/ProducerProxyBeanFactory.java
> +            if (!kafkaProducer.encryptionPassword().isEmpty() || !kafkaProducer.encryptionSalt().isEmpty()) {
Fixed.

2022-03-23 11:53 UTC, marcus-j approved these changes

2024-10-23 10:59 UTC, merged